### ISSUE TITLE
Issue with interaction between edge router and add-on

### ISSUE THREAD

**Issue by Gyosa3** [lmagyar/homeassistant-addon-tailscale#104]
Hello,

I've been running your forked add-on for a while now, and migrated to the community add-on now that all interesting features have been integrated. Great work!

I have a question for you, maybe you will spot what I cannot understand in my setup. I just noticed this while migrating to the official add-on this week.

Here is my network topology spread over two geographically separated sites:

![Schema global tailscale](https://github.com/lmagyar/homeassistant-addon-tailscale/assets/51777889/d5156a4f-33fe-43e8-bc5d-1db80df77ce8)

Everything is working well, the only thing that I do not understand is why the .5.3 add-on node is not working as an exit node when the parameter "Source SNAT subnet route" is set to "false". When this parameter is set to "false", all site-to-site traffic is working well, but the exit-node traffic does not go through, either from a local machine in LAN site B, or from an external device running the Tailscale client with exit-node configuration.

A traceroute shows that it leaves the .5.3 HA machine to the local edge router and does not come back.

On the other hand, the .2.6 add-on node on the other side (same addon version 0.14, same HA version, same setup) is working with "Source SNAT subnet route" set to "false" and can be used as an exit node by external devices connected to tailscale.

On my router in site A, I have the following static routes sent to the .5.3 HA addon:
192.168.2.0, 192.168.3.0, 192.168.4.0, 192.168.95.0 and 100.64.0.0

On my router in site B, I have the following static routes sent to the .2.6 HA addon:
192.168.5.0 and 100.64.0.0

Router on site A is a Netgear R8500, router on site B is an Ubiquity Dream Machine Pro, so they may work differently.

I have excluded DNS issue as an external device running Tailscale is resolving names via 100.100.100.100 and it gets the resolved IP correctly. So it is the real traffic that does not come back when the source IP is not snat-ed by the .5.3 addon, although the router and the HA node both have the routing tables to route back the traffic to any node or device that can use the exit-node feature.

So I'm puzzled. Any clue? Thanks!

**Comment by lmagyar** [comment]
I would put my money on the different routers. My random ideas:
- I don't understand, why 100.x.x.x is configured on your edge routers, these address are only valid inside the tailnet. But the tailnet is a virtual network, no packages on real LANs should have these addresses. Plus ISP-s can use these 100.x.x.x addresses for CG-NAT, maybe, maybe this is the reason.
- "leaves the .5.3 HA machine to the local edge router and does not come back" I would use the "heavy artillery", Wireshark or similar to see the packages between HA.5.3 and it's router, then between HA.2.6 and it's router, maybe you can see some difference, maybe some configuration settings are still different. Or it can prove, that the routers handle these packages differently.

Note, I'm not a net-admin, my experiences are quite basic, and I have no experience with Netgear or Ubiquity.

**Comment by Gyosa3** [comment]
Hello, yes I have also been surprised that the tailscale network should be explicitly routed but this is per the documentation from the tailscale website (extract below). I think it is relevant when the source-snat-route setting is set to "false", which possibly let packets on the local network with a 100.x IP address. I have tested that if I do not add this route, I cannot connect to a local machine in LAN A or B from a machine on the internet connecting via Tailnet, while I still can connect between A and B. So this route is really necessary on all sides of the extended network for the remote devices.

Having said that, it is true that the issue comes with packets issued by a remote device (which wants to use the exit node on site A or B) so packets with a source IP in the range of 100.x when source-snat is disabled. So the routers on both sides may treat these packets differently, one would accept to NAT this range of IPs the other one no, for any reason. I'll do some wireshark on the occasion, yes, and touch nothing while it works...

thanks!

```
[Step 3: Configure the non-Tailscale devices ](https://tailscale.com/kb/1214/site-to-site#step-3-configure-the-non-tailscale-devices)

On each non-Tailscale device on the 10.0.0.0/20 subnet that you want to connect, you need to add a static route to the tailnet and to the remote 10.118.48.0/20 LAN:

ip route add 100.64.0.0/10 via 10.0.0.2
ip route add 10.118.48.0/20 via 10.0.0.2

Likewise on each device on the 10.118.48.0/20 subnet that you want to connect, add a static route to the tailnet and to the remote 10.0.0.0/20 LAN:

ip route add 100.64.0.0/10 via 10.118.48.2
ip route add 10.0.0.0/20 via 10.118.48.2

Alternatively, the settings in this step can be set in your cloud environment routing, or on most routers by adding a [“next hop”](https://en.wikipedia.org/wiki/Hop_(networking)#Next_hop) static route. For any of these techniques, you are selecting the remote network subnet as the target, and the LAN IP address of the local Tailscale subnet router as the router.
```

**Comment by lmagyar** [comment]
Oh, yes, now I understand the 100.x.x.x routing.

Did you check the external IP of the router on LAN A? Maybe the ISP uses CG-NAT, and it has 100.x.x.x address also on it's external interface.

**Comment by lmagyar** [comment]
Just a note: from TS 1.66.0 you will need to disable stateful_filtering. See: #127

**Comment by lmagyar** [comment]
Closing, because there is no reply what was the solution.
