### ISSUE TITLE
Funnel serving the wrong port?

### ISSUE THREAD

**Issue by AdnerVL** [lmagyar/homeassistant-addon-tailscale#21]
When I try to access mt HA using the funnel I get this error: 400: Bad Request
Maybe funnel is serving the wrong port? How can I change the port?
Thanks

**Comment by lmagyar** [comment]
Currently it is fix, 443. Even when you access it from the internet or when access it within the tailnet. Tailscale has plans to make a UI to make it configurable, so until they do it, I just used the fix 443 standard SSL port.

**Comment by lmagyar** [comment]
Can you access it within the tailnet, when the Tailscale client is connected?
If you configured it just now, Funnel needs a few minutes to get all the DNS and other setting ready.
And sometimes it needs to delete the browser cache, once I had to restart Chrome when I experimented all the settings and Chrome got really confused. :)

**Comment by AdnerVL** [comment]
Tailscale section was okay, my issue was I forgot to put:
`http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 127.0.0.1`
  on the home assistant yaml config file

**Comment by hephaestic** [comment]
> Tailscale section was okay, my issue was I forgot to put: `http: use_x_forwarded_for: true trusted_proxies: - 127.0.0.1` on the home assistant yaml config file

Can you elaborate on this solution? Im running into this same error
