### ISSUE TITLE
Option to use Tailsacle Subnets?

### ISSUE THREAD

**Issue by austinliuu** [lmagyar/homeassistant-addon-tailscale#4]
Is it possible to have the addon to use the Tailscale subnets? Although it looks like the original addon does not support that

**Comment by lmagyar** [comment]
The original add-on advertised only the default interface (ha network info default, usually eth0), this fork uses all the supported interfaces (ha network info, eg. eth0, wlan0), and at https://login.tailscale.com/admin/machines we can enable the subnet routes, and exit node function.

I intentionally limited it only to use the supported interface list, this way it has a chance that get merged, in case of the samba add-on, the "running all the available interfaces" version was not allowed. Though the meaning of the "supported" is a bit unclear for me, these are the interfaces that the Supervisor manages.

**Comment by austinliuu** [comment]
I have other devices who broadcast a different subnet, but don't see the option there for now and other devices at the other subnet can't be pinged. Do you know if that is a option?

**Comment by lmagyar** [comment]
Oh, do you want to access other devices from this device (which runs this Tailscale add-on)? As I understand this is not possible, the add-on is running in userspace networking (`options+=(--tun=userspace-networking`) is hard wired), so it doesn't create a network interface that's visible from other containers, so its not possible to route traffic (see https://tailscale.com/kb/1112/userspace-networking/).

Try: https://github.com/tsujamin/hass-addons That add-on has all the possibility to fine-tune, though that is the exact opposite of the "zero config" philosophy of this add-on. As I remember they run by default **not** in userspace-networking, but this causes other problems, and they are already planning to change to default on userspace-networking mode.

**Comment by lmagyar** [comment]
I've read again the https://tailscale.com/kb/1112/userspace-networking/ documentation and added the SOCKS5 and HTTP outbound proxies for experimentation, and it works great, soon I will release it. :)

**Comment by lmagyar** [comment]
New version is out, you can test it.
