### ISSUE TITLE
Possible improvements to proxy functionality

### ISSUE THREAD

**Issue by elcajon** [lmagyar/homeassistant-addon-tailscale#45]
With the last couple tailscale releases there were a few changes we can incorporate to enhance functionality. (I can also create a PR if you want me to).

https://github.com/lmagyar/homeassistant-addon-tailscale/blob/de758625e3fd0ae7d2dba335e0ad8bec8bcd3913/tailscale/rootfs/etc/s6-overlay/s6-rc.d/proxy/run#L20-L24

We could achieve proxying to (self signed) https ports without checking the certificate by using this command ([reference](https://github.com/tailscale/tailscale/issues/8421)):
`tailscale serve https / https+insecure://127.0.0.1:$(bashio::core.port)`

I haven't tested this for HA, but it works for my (self signed) Proxmox host.

https://github.com/lmagyar/homeassistant-addon-tailscale/blob/de758625e3fd0ae7d2dba335e0ad8bec8bcd3913/tailscale/rootfs/etc/s6-overlay/s6-rc.d/proxy/run#L29-L30
Could be fixed by running `tailscale serve reset` (at the beginning of the script)
 
Enjoy the vacation, the topics are not urgent. 😉

**Comment by lmagyar** [comment]
I finally added these things to the v0.11.1.11 release.
Reset: https://github.com/hassio-addons/addon-tailscale/compare/main...lmagyar:homeassistant-addon-tailscale:draft-pr-reset-proxy-config
Https: https://github.com/hassio-addons/addon-tailscale/compare/main...lmagyar:homeassistant-addon-tailscale:draft-pr-allow-proxy-to-https-ha

Though I didn't create a PR for them, I will, but only after all the other stuffs are merged. :/

Oh, and thank you for the ideas! :)

**Comment by lmagyar** [comment]
I finally tested this https+insecure protocol, this is for self signed certificates but can't help proxying https.

This works with plain http:
```
curl -v -o /dev/null -w "%{http_code}\n" --resolve dummy:80:127.0.0.1 "http://dummy:80"
```

The https equivalent would be:
```
curl -v -o /dev/null -w "%{http_code}\n" --insecure --resolve dummy:443:127.0.0.1 "https://dummy:443"
```

But this gives the below error due to SNI mismatch:
```
curl: (35) OpenSSL/3.1.2: error:0A000458:SSL routines::tlsv1 unrecognized name
```

And when I use:
```
/opt/tailscale serve https:444 / "https+insecure://127.0.0.1:443"
```

This fails with unrecognized name also:
```
http: proxy error: remote error: tls: unrecognized name
```

So tailscale fails with the exact same error.

I will remove this https proxying, because this is good for self-signed certs only, and this has no use-case in case of HA in my opinion.
