### ISSUE TITLE
Cannot connect to remote server

### ISSUE THREAD

**Issue by a8ree** [lmagyar/homeassistant-addon-tailscale#49]
Hi @lmagyar 

I've installed your add-on but I don't see any difference in behavour to the main codebase

I am unable to ping or connect via SMB to the remote server. I've opened up terminal and am trying to connect via IP. I've successfully connected from another devices on the same tailscale network to the remote server without issue.

Here is the log

2023/07/30 18:18:41 requestEngineStatusAndWait: waiting...
2023/07/30 18:18:41 requestEngineStatusAndWait: got status update.
2023/07/30 18:18:41 stopEngineAndWait: done.
2023/07/30 18:18:41 control: doLogin(regen=false, hasUrl=true)
2023/07/30 18:18:41 control: RegisterReq: onode= node=[tpQJV] fup=true nks=false
2023/07/30 18:18:47 control: RegisterReq: got response; nodeKeyExpired=false, machineAuthorized=true; authURL=false
2023/07/30 18:18:47 blockEngineUpdates(false)
2023/07/30 18:18:47 control: netmap: got new dial plan from control
2023/07/30 18:18:47 active login:xxx@gmail.com
2023/07/30 18:18:47 Switching ipn state NeedsLogin -> Starting (WantRunning=true, nm=true)
2023/07/30 18:18:47 magicsock: SetPrivateKey called (init)
2023/07/30 18:18:47 wgengine: Reconfig: configuring userspace WireGuard config (with 0/3 peers)
2023/07/30 18:18:47 wgengine: Reconfig: configuring router
2023/07/30 18:18:47 wgengine: Reconfig: configuring DNS
2023/07/30 18:18:47 dns: Set: {DefaultResolvers:[] Routes:{xxx-halfmoon.ts.net.:[] ts.net.:[199.247.155.53 2620:111:8007::53]}+65arpa SearchDomains:[pig-halfmoon.ts.net.] Hosts:4}
2023/07/30 18:18:47 peerapi: serving on http://100.97.46.29:40432
2023/07/30 18:18:47 peerapi: serving on http://[fd7a:115c:a1e0:ab12:4843:cd96:6261:2e1d]:40432
2023/07/30 18:18:47 health("dns-os"): error: getting OS base config is not supported
2023/07/30 18:18:47 health("dns"): error: getting OS base config is not supported
2023/07/30 18:18:47 portmapper: UPnP meta changed: {Location:http://192.168.1.1:52793/rootDesc.xml Server:AsusWRT/384.13 UPnP/1.1 MiniUPnPd/2.1 USN:uuid:3ddcd1d3-2380-45f5-b069-704d7b93f2e0::urn:schemas-upnp-org:device:InternetGatewayDevice:1}
2023/07/30 18:18:47 magicsock: home is now derp-8 (lhr)
2023/07/30 18:18:47 magicsock: adding connection to derp-8 for home-keep-alive
2023/07/30 18:18:47 control: NetInfo: NetInfo{varies=false hairpin=true ipv6=false ipv6os=true udp=true icmpv4=false derp=#8 portmap=active-UMC link=""}
2023/07/30 18:18:47 magicsock: 1 active derp conns: derp-8=cr0s,wr0s
Success.
2023/07/30 18:18:47 Switching ipn state Starting -> Running (WantRunning=true, nm=true)
2023/07/30 18:18:47 derphttp.Client.Connect: connecting to derp-8 (lhr)
[18:18:47] INFO: Tailscale is running
2023/07/30 18:18:47 magicsock: endpoints changed: 82.17.103.210:51482 (portmap), 172.19.0.1:51482 (local), 172.20.0.1:51482 (local), 172.23.0.1:51482 (local), 172.30.32.1:51482 (local), 172.30.232.1:51482 (local), 192.168.1.5:51482 (local)
s6-rc: info: service post-tailscaled successfully started
s6-rc: info: service proxy: starting
s6-rc: info: service taildrop: starting
s6-rc: info: service taildrop successfully started
[18:18:47] NOTICE: Tailscale's HTTPS support is disabled, therefore add-on's Tailscale Proxy functionality is disabled
s6-rc: info: service proxy successfully started
s6-rc: info: service funnel: starting
[18:18:47] NOTICE: Tailscale's HTTPS support is disabled, therefore add-on's Tailscale Funnel functionality is disabled
s6-rc: info: service funnel successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
2023/07/30 18:18:47 magicsock: derp-8 connected; connGen=1
2023/07/30 18:40:45 monitor: RTM_DELROUTE: src=, dst=fe80::/128, gw=, outif=511, table=254
2023/07/30 18:40:45 monitor: RTM_DELROUTE: src=, dst=fe80::301e:88ff:fe7d:78ee/128, gw=, outif=511, table=254
2023/07/30 18:40:45 monitor: RTM_DELROUTE: src=, dst=fe80::/64, gw=, outif=511, table=254
2023/07/30 18:40:45 monitor: RTM_DELROUTE: src=, dst=ff00::/8, gw=, outif=511, table=254
2023/07/30 19:26:30 wgengine: Reconfig: [zAQRG] changed from "discokey:c9779583efd38f22215ebdeb56b648dcd74848d38e8a32deeb6860086b5f8374" to "discokey:6f05c9b6b0bce60001ec7e281a853e284bb4daac9a58c313b4cb58fc6435d73b"
2023/07/30 21:40:45 monitor: RTM_DELROUTE: src=, dst=fe80::/128, gw=, outif=513, table=254
2023/07/30 21:40:45 monitor: RTM_DELROUTE: src=, dst=fe80::9431:4eff:fecf:e814/128, gw=, outif=513, table=254
2023/07/30 21:40:45 monitor: RTM_DELROUTE: src=, dst=fe80::/64, gw=, outif=513, table=254
2023/07/30 21:40:45 monitor: RTM_DELROUTE: src=, dst=ff00::/8, gw=, outif=513, table=254
2023/07/31 00:05:33 control: netmap: got new dial plan from control
2023/07/31 00:40:44 monitor: RTM_DELROUTE: src=, dst=fe80::/128, gw=, outif=515, table=254
2023/07/31 00:40:44 monitor: RTM_DELROUTE: src=, dst=fe80::fc9a:44ff:fea0:3a1e/128, gw=, outif=515, table=254
2023/07/31 00:40:44 monitor: RTM_DELROUTE: src=, dst=fe80::/64, gw=, outif=515, table=254
2023/07/31 00:40:44 monitor: RTM_DELROUTE: src=, dst=ff00::/8, gw=, outif=515, table=254
2023/07/31 03:02:39 wgengine: Reconfig: [zAQRG] changed from "discokey:6f05c9b6b0bce60001ec7e281a853e284bb4daac9a58c313b4cb58fc6435d73b" to "discokey:9e7fc1b08847571aa5d27eb05ce77061f4281cf8849c2d6dd84b734be8838851"
2023/07/31 03:40:46 monitor: RTM_DELROUTE: src=, dst=fe80::/128, gw=, outif=517, table=254
2023/07/31 03:40:46 monitor: RTM_DELROUTE: src=, dst=fe80::e8d1:f9ff:fe78:724e/128, gw=, outif=517, table=254
2023/07/31 03:40:46 monitor: RTM_DELROUTE: src=, dst=fe80::/64, gw=, outif=517, table=254
2023/07/31 03:40:46 monitor: RTM_DELROUTE: src=, dst=ff00::/8, gw=, outif=517, table=254
2023/07/31 06:40:48 monitor: RTM_DELROUTE: src=, dst=fe80::/128, gw=, outif=519, table=254
2023/07/31 06:40:48 monitor: RTM_DELROUTE: src=, dst=fe80::b029:fcff:fe8f:43a6/128, gw=, outif=519, table=254
2023/07/31 06:40:48 monitor: RTM_DELROUTE: src=, dst=fe80::/64, gw=, outif=519, table=254
2023/07/31 06:40:48 monitor: RTM_DELROUTE: src=, dst=ff00::/8, gw=, outif=519, table=254
2023/07/31 09:40:51 monitor: RTM_DELROUTE: src=, dst=fe80::/128, gw=, outif=521, table=254
2023/07/31 09:40:51 monitor: RTM_DELROUTE: src=, dst=fe80::bc64:28ff:fe20:3a5c/128, gw=, outif=521, table=254
2023/07/31 09:40:51 monitor: RTM_DELROUTE: src=, dst=fe80::/64, gw=, outif=521, table=254
2023/07/31 09:40:51 monitor: RTM_DELROUTE: src=, dst=ff00::/8, gw=, outif=521, table=254
2023/07/31 12:40:53 monitor: RTM_DELROUTE: src=, dst=fe80::/128, gw=, outif=523, table=254
2023/07/31 12:40:53 monitor: RTM_DELROUTE: src=, dst=fe80::54e4:84ff:feca:211a/128, gw=, outif=523, table=254
2023/07/31 12:40:53 monitor: RTM_DELROUTE: src=, dst=fe80::/64, gw=, outif=523, table=254
2023/07/31 12:40:53 monitor: RTM_DELROUTE: src=, dst=ff00::/8, gw=, outif=523, table=254
2023/07/31 15:40:53 monitor: RTM_DELROUTE: src=, dst=fe80::/128, gw=, outif=525, table=254
2023/07/31 15:40:53 monitor: RTM_DELROUTE: src=, dst=fe80::f067:e7ff:fe89:d02c/128, gw=, outif=525, table=254
2023/07/31 15:40:53 monitor: RTM_DELROUTE: src=, dst=fe80::/64, gw=, outif=525, table=254
2023/07/31 15:40:53 monitor: RTM_DELROUTE: src=, dst=ff00::/8, gw=, outif=525, table=254
2023/07/31 15:42:03 control: netmap: got new dial plan from control
2023/07/31 15:42:50 control: netmap: got new dial plan from control
2023/07/31 15:47:20 monitor: RTM_NEWROUTE: src=, dst=fd61:298a:f5e3:1::/64, gw=fe80::5f57:7775:e20e:8df1, outif=2, table=254
2023/07/31 15:47:20 monitor: RTM_DELROUTE: src=, dst=fd5d:5954:4b9:1::/64, gw=fe80::5f57:7775:e20e:8df1, outif=2, table=254
2023/07/31 15:47:21 monitor: RTM_NEWROUTE: src=, dst=fd61:298a:f5e3:1::/64, gw=, outif=0, table=254
2023/07/31 15:47:21 monitor: RTM_DELROUTE: src=, dst=fd5d:5954:4b9:1::/64, gw=fe80::db8a:dab0:2ee:b6cb, outif=2, table=254
2023/07/31 15:47:23 monitor: RTM_NEWROUTE: src=, dst=fd61:298a:f5e3:1::/64, gw=, outif=0, table=254
2023/07/31 15:47:23 [RATELIMIT] format("monitor: %s: src=%v, dst=%v, gw=%v, outif=%v, table=%v")
2023/07/31 16:01:57 monitor: RTM_DELROUTE: src=, dst=fd61:298a:f5e3:1::/64, gw=fe80::e683:27bc:4db0:212, outif=2, table=254
2023/07/31 16:01:59 monitor: RTM_NEWROUTE: src=, dst=fd5d:5954:4b9:1::/64, gw=, outif=0, table=254
2023/07/31 16:01:59 monitor: RTM_DELROUTE: src=, dst=fd61:298a:f5e3:1::/64, gw=fe80::db8a:dab0:2ee:b6cb, outif=2, table=254
2023/07/31 16:01:59 monitor: RTM_NEWROUTE: src=, dst=fd5d:5954:4b9:1::/64, gw=, outif=0, table=254
2023/07/31 16:01:59 monitor: RTM_DELROUTE: src=, dst=fd61:298a:f5e3:1::/64, gw=fe80::5f57:7775:e20e:8df1, outif=2, table=254
2023/07/31 16:01:59 [RATELIMIT] format("monitor: %s: src=%v, dst=%v, gw=%v, outif=%v, table=%v")
2023/07/31 18:40:55 monitor: RTM_DELROUTE: src=, dst=fe80::/128, gw=, outif=527, table=254
2023/07/31 18:40:55 monitor: RTM_DELROUTE: src=, dst=fe80::1877:75ff:feab:a/128, gw=, outif=527, table=254
2023/07/31 18:40:55 monitor: RTM_DELROUTE: src=, dst=fe80::/64, gw=, outif=527, table=254
2023/07/31 18:40:55 monitor: RTM_DELROUTE: src=, dst=ff00::/8, gw=, outif=527, table=254
2023/07/31 18:40:56 magicsock: home is now derp-4 (fra)
2023/07/31 18:40:56 magicsock: adding connection to derp-4 for home-keep-alive
2023/07/31 18:40:56 control: NetInfo: NetInfo{varies=false hairpin=true ipv6=false ipv6os=true udp=true icmpv4=false derp=#4 portmap=active-UMC link=""}
2023/07/31 18:40:56 magicsock: 2 active derp conns: derp-4=cr0s,wr0s derp-8=cr24h22m0s,wr24h22m0s
2023/07/31 18:40:56 derphttp.Client.Recv: connecting to derp-4 (fra)
[further tailscaled logs suppressed, set add-on's configuration option 'log_level' to 'debug' to see further tailscaled logs]

Let me know if you can see anything that may explain

Cheers

**Comment by lmagyar** [comment]
What is the config of the add-on? Did you add `userspace_networking: false` to the config?

This is not enabled by default.

**Comment by a8ree** [comment]
Ah, I thought I was setting that under 'Show unused optional configuration options' but I've edited the YAML and now it is working!
Many thanks - Ping works, and media share mapped!

**Comment by lmagyar** [comment]
Yeah, as I remember this is a UI bug, if you click `Show unused optional configuration options` then you can't set the options to `false` immediately, first you have to set `true`, then `false`, then save it, but I prefer to see the .yaml before saving it. :)
