### ISSUE TITLE
Feature Request: Store Proxy Certificate in /ssl/

### ISSUE THREAD

**Issue by Aaroneisele55** [lmagyar/homeassistant-addon-tailscale#68]
Hello,

I would like to request the addition of a feature to save the SSL certificate from the Proxy feature under the /ssl/ directory for use with the SSL features of some HA Add-Ons.

I would be really grateful if this gets implemented 

Best regards
Aaron

**Comment by lmagyar** [comment]
It seems tricky:
- `tailscale serve` (ie. the proxy) automatically updates/renews the cert, but the file location is hard wired
- `tailscale cert` can save the cert anywhere, but won't update it

The only solution I see now is to create another internal service in the add-on, that uses `inotifywait`, or `entr`, or `incron` to:
- detect when the cert/key file changes, and copy it
- detect with some black magic when the machine name or domain changes and a new cert is created, and copy the new files

Don't you know some trick to avoid this complicated solution?

**Comment by Aaroneisele55** [comment]
> It seems tricky:
> 
>     * `tailscale serve` (ie. the proxy) automatically updates/renews the cert, but the file location is hard wired
> 
>     * `tailscale cert` can save the cert anywhere, but won't update it
> 
> 
> The only solution I see now is to create another internal service in the add-on, that uses `inotifywait`, or `entr`, or `incron` to:
> 
>     * detect when the cert/key file changes, and copy it
> 
>     * detect with some black magic when the tailscale machine name or domain changes and a new cert is created, and copy the new files
> 
> 
> Don't you know some trick to avoid this complicated solution?

Couldn't we just periodically renew the cert using tailscale cert, e.g on a daily basis, and have a button in the web UI that manually regenerates it? 
That way, we can save the file e.g in /ssl/ where most HA add-ons expect it, and the auto-renewal is handled by that schedule too

**Comment by lmagyar** [comment]
Yes, I used periodical restart in the NGINX proxy add-on on cert renewal, but there the host/file names are not changed on the fly.

Finally I've implemented it. The only strange thing is, that I can't call the config of this function like
```
proxy:
  certfile: str?
  keyfile: str?
```
because `proxy: true/false` is already used in the config.

I can't call it
```
lets_encrypt:
  certfile: str?
  keyfile: str?
```
because there is a bug in the Supervisor/UI ([#4606](https://github.com/home-assistant/supervisor/issues/4606) and [#2640](https://github.com/home-assistant/supervisor/issues/2640)), and even these are optional, the UI won't let save a config without them.

So I went with the strange
```
lets_encrypt_certfile: str?
lets_encrypt_keyfile: str?
```
options. If the issues above got fixed in the future, this can be changed back to something better.

---

***It is ready to be released, but I'm waiting for a new bugfix release of the original add-on to sync the source. I hope it will be out within a day or two.***

**Comment by lmagyar** [comment]
I finally released it here, I will create a non-draft PR in the official repo later (currently the PR is draft, there are more important bugfixes in the official queue).

**Comment by lmagyar** [comment]
New version is out, closing.

**Comment by lmagyar** [comment]
Reopened it, because the PR in the official repo got rejected. I think some misunderstanding.

So why do you need this feature, how do you use it, which other add-on uses this cert for what, why?

**Comment by Aaroneisele55** [comment]
> Reopened it, because the PR in the official repo got rejected. I think some misunderstanding.
> 
> So why do you need this feature, how do you use it, which other add-on uses this cert for what, why?

I use it for the Adguard Home add-on's encryption feature so I can use my Android phone's "private DNS" feature.

**Comment by lmagyar** [comment]
Frank's reply: "Those will have a similar faith in the long run. I've already start removing that feature from add-ons."

To be honest, I can't imagine how will my DuckDNS add-on generated certs work under the NGINX reverse proxy add-on without the intermediate /ssl folder storage. OK, those are not community add-ons, but "official" add-ons, maybe not affected?

I didn't find any docs (like https://github.com/home-assistant/architecture/discussions or https://github.com/home-assistant/architecture/tree/master/adr) on this decision, so I will wait and see.

Meantime this feature remains in this fork. After the original Tailscale add-on gets regular updates, I will slow down on maintaining this fork, but this will happen I think only next year. We will see.
