### ISSUE TITLE
On / Off / On / Off - Stuck in loop 

### ISSUE THREAD

**Issue by hallerdavid** [lmagyar/homeassistant-addon-tailscale#69]
Like requested, here is my log - the add-on restarts every few second when watchdog is activated, if not - it will just stop and that was it.

2023/10/02 18:08:15 Doing edit: MaskedPrefs{WantRunning=true AdvertiseRoutes=[0.0.0.0/0 ::/0 10.10.30.0/24 fd2f:daf1:292:4378::/64]}
2023/10/02 18:08:15 tailscaleUp(reauth=true, logout=false) ...
2023/10/02 18:07:39 stopEngineAndWait: done.
2023/10/02 18:08:15 Start
2023/10/02 18:08:15 control: client.Shutdown()
2023/10/02 18:08:15 control: client.Shutdown
2023/10/02 18:08:15 control: updateRoutine: exiting
2023/10/02 18:08:15 control: mapRoutine: exiting
2023/10/02 18:08:15 control: authRoutine: exiting
2023/10/02 18:08:15 control: Client.Shutdown done.
2023/10/02 18:08:15 Backend: logs: be:a442173f8ba38ace86ecddf70b29dc735594300beadab0219e50381de804fc9d fe:
2023/10/02 18:08:15 Switching ipn state NoState -> NeedsLogin (WantRunning=true, nm=false)
2023/10/02 18:08:15 blockEngineUpdates(true)
2023/10/02 18:08:15 StartLoginInteractive: url=false
2023/10/02 18:08:15 control: client.Login(false, 2)
2023/10/02 18:08:15 control: LoginInteractive -> regen=true
2023/10/02 18:08:15 control: doLogin(regen=true, hasUrl=false)
2023/10/02 18:08:15 control: control server key from https://controlplane.tailscale.com: ts2021=[fSeS+], legacy=[nlFWp]
2023/10/02 18:08:15 control: Generating a new nodekey.
2023/10/02 18:08:15 control: RegisterReq: onode= node=[bJrGg] fup=false nks=false
2023/10/02 18:08:15 control: RegisterReq: got response; nodeKeyExpired=false, machineAuthorized=false; authURL=true
2023/10/02 18:08:15 control: AuthURL is https://login.tailscale.com/a/df402f8bfad7
2023/10/02 18:08:15 control: doLogin(regen=false, hasUrl=true)
2023/10/02 18:08:15 Received auth URL: https://login.tailsc...
2023/10/02 18:08:15 popBrowserAuthNow: url=true
2023/10/02 18:08:15 blockEngineUpdates(true)
2023/10/02 18:08:15 stopEngineAndWait...
2023/10/02 18:08:15 control: RegisterReq: onode= node=[bJrGg] fup=true nks=false
To authenticate, visit:
	https://login.tailscale.com/a/df402f8bfad7
2023/10/02 18:08:15 tailscaleUp = (URL true, <nil>)
2023/10/02 18:08:15 requestEngineStatusAndWait
2023/10/02 18:08:15 requestEngineStatusAndWait: waiting...
2023/10/02 18:08:15 requestEngineStatusAndWait: got status update.
2023/10/02 18:08:15 stopEngineAndWait: done.
2023/10/02 18:08:21 control: RegisterReq: got response; nodeKeyExpired=false, machineAuthorized=true; authURL=false
2023/10/02 18:08:21 blockEngineUpdates(false)
2023/10/02 18:08:21 control: netmap: got new dial plan from control
2023/10/02 18:08:21 active login: hallerdavid@github
2023/10/02 18:08:21 Switching ipn state NeedsLogin -> Starting (WantRunning=true, nm=true)
2023/10/02 18:08:21 magicsock: SetPrivateKey called (init)
2023/10/02 18:08:21 monitor: gateway and self IP changed: gw=10.10.30.1 self=10.10.30.30
2023/10/02 18:08:21 wgengine: Reconfig: configuring userspace WireGuard config (with 2/8 peers)
2023/10/02 18:08:21 wgengine: Reconfig: configuring router
2023/10/02 18:08:21 wgengine: Reconfig: configuring DNS
2023/10/02 18:08:21 dns: Set: {DefaultResolvers:[] Routes:{tailfb0c8.ts.net.:[] ts.net.:[199.247.155.53 2620:111:8007::53]}+65arpa SearchDomains:[tailfb0c8.ts.net.] Hosts:9}
2023/10/02 18:08:21 health("dns"): error: getting OS base config is not supported
2023/10/02 18:08:21 health("dns-os"): error: getting OS base config is not supported
2023/10/02 18:08:21 peerapi: serving on http://100.86.247.84:59783
2023/10/02 18:08:21 peerapi: serving on http://[fd7a:115c:a1e0:ab12:4843:cd96:6256:f754]:59783
Success.
[18:08:21] INFO: Tailscale is running
2023/10/02 18:08:21 Switching ipn state Starting -> Running (WantRunning=true, nm=true)
2023/10/02 18:08:21 magicsock: home is now derp-4 (fra)
2023/10/02 18:08:21 magicsock: adding connection to derp-4 for home-keep-alive
2023/10/02 18:08:21 magicsock: 1 active derp conns: derp-4=cr0s,wr0s
2023/10/02 18:08:21 control: NetInfo: NetInfo{varies=false hairpin=false ipv6=false ipv6os=true udp=true icmpv4=false derp=#4 portmap= link="" firewallmode=""}
2023/10/02 18:08:21 derphttp.Client.Connect: connecting to derp-4 (fra)
2023/10/02 18:08:21 magicsock: endpoints changed: 92.117.194.15:60366 (stun), 10.10.30.30:60366 (local), 172.30.32.1:60366 (local), 172.30.232.1:60366 (local)
[18:08:22] WARNING: The connection's key will expire on: 2024-03-30T16:08:21Z
[18:08:22] WARNING: Consider disabling key expiry to avoid losing connection to your Home Assistant device.
[18:08:22] WARNING: Please check your configuration based on the add-on's Documentation under "Configuration"
s6-rc: info: service post-tailscaled successfully started
s6-rc: info: service proxy: starting
s6-rc: info: service taildrop: starting
s6-rc: info: service taildrop successfully started
[18:08:23] ERROR: Unable to connect to Home Assistant on http://127.0.0.1:8123
[18:08:23] ERROR: Please check your configuration based on the add-on's Documentation under "Option: proxy"
s6-rc: warning: unable to start service proxy: command exited 1
/run/s6/basedir/scripts/rc.init: warning: s6-rc failed to properly bring all the services up! Check your logs (in /run/uncaught-logs/current if you have in-container logging) for more information.
/run/s6/basedir/scripts/rc.init: fatal: stopping the container.
s6-rc: info: service taildrop: stopping
s6-rc: info: service nginx: stopping
[18:08:23] INFO: Service taildrop exited with code 256 (by signal 15)
s6-rc: info: service taildrop successfully stopped
s6-rc: info: service post-tailscaled: stopping
s6-rc: info: service post-tailscaled successfully stopped
s6-rc: info: service tailscaled: stopping
[18:08:23] INFO: Service NGINX exited with code 0 (by signal 0)
s6-rc: info: service nginx successfully stopped
s6-rc: info: service init-nginx: stopping
s6-rc: info: service web: stopping
s6-rc: info: service init-nginx successfully stopped
[18:08:23] INFO: Service tailscaled exited with code 256 (by signal 15)
s6-rc: info: service tailscaled successfully stopped
[18:08:23] INFO: Service Tailscale web exited with code 256 (by signal 15)
s6-rc: info: service web successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service base-addon-log-level: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service base-addon-log-level successfully stopped
s6-rc: info: service base-addon-banner: stopping
s6-rc: info: service base-addon-banner successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped

**Comment by hallerdavid** [comment]
fixed by reading the log.... :-) just added the section for the proxy to the configuration.yaml

**Comment by lmagyar** [comment]
Yesssss. :) You were faster than me with a few seconds. :D
