### ISSUE TITLE
ping is not possible

### ISSUE THREAD

**Issue by hallerdavid** [lmagyar/homeassistant-addon-tailscale#70]
i tried your fork because i need to ping tailscale devices from the HomeAssistantOS (I want to use remote home-assistant and i installed tailscale fork from you on both of my HassOS devices. but i cant ping one from the other.)

Can you help?

**Comment by lmagyar** [comment]
Please add to the config:
```
userspace_networking: false
```

By default there is no `tailscale0` interface to route traffic outward, because it can cause problems, though there are solutions in this add-on to fix those problems, and they are working, so maybe the default will be `false` in the future.

**Comment by hallerdavid** [comment]
this worked! thank you <3

**Comment by lmagyar** [comment]
I've also added a warning in the log when userspace networking is used. It will be part of the next version.

> bashio::log.warning "The add-on uses userspace networking mode."
> bashio::log.warning "If you need to access other clients on your tailnet from your Home Assistant instance,"
> bashio::log.warning "disable userspace networking mode, that will create a \"tailscale0\" network interface on your host."
> bashio::log.warning "Please check your configuration based on the add-on's Documentation under \"Option: userspace_networking\""

It is really good to see first time users' problems to find these weak points in the docs/code.
