### ISSUE TITLE
Cannot disable funnel feature

### ISSUE THREAD

**Issue by TimDowker** [lmagyar/homeassistant-addon-tailscale#72]
I've set the option to disable the funnel feature but it will not deactivate.  I've restarted the add-on.  My config is

accept_routes: true
userspace_networking: false
advertise_exit_node: false
proxy: false
funnel: false
taildrop: false

Also cannot disable "advertise_routes" - when I try to enter "advertise_routes: false" the add-on will not save the config.

**Comment by lmagyar** [comment]
On the "funnel feature will not deactivate" issue: it was reported in the official repo also, see https://github.com/hassio-addons/addon-tailscale/issues/272

Now I can't figure out how "it worked for me"...

Anyway, a bugfix PR is ready to be merged in the original repo, I will release it here also (I'm waiting for the new bugfix release of the original add-on to sync the source).

**Comment by lmagyar** [comment]
New version is out, closing.
