### ISSUE TITLE
Readonly web interface

### ISSUE THREAD

**Issue by lmagyar** [lmagyar/homeassistant-addon-tailscale#97]
Currently the web UI is in read-only mode. (That is another story, if we manage to make it non-read-only and it starts to conflict with the add-on settings, we will cross that river when we are there.)

If we access the web UI from a browser that has access through the tailnet to the web server, it works.

I've tried to figure out how to access the web UI over LAN (without NGINX reverse proxy, without tailnet access under the browser, just a plain PC on the same LAN), but even the below minimal config didn't worked (chrome network logs seemed to me to access the same API, response received with the correct data, but trivially something was different because only a "Page not found" was displayed, but I'm not a web developer and can't figure out the root cause):

```
/opt/tailscale web --listen 192.168.1.8:8088 --prefix 'http://192.168.1.8:8088/'
```

Access it from LAN with `http://192.168.1.8:8088/`

**Comment by lmagyar** [comment]
Later, when non-read-only UI works:
1. drop advertise_exit_node, drop any code that manipulates exit node settings
1. drop advertise_routes, drop any code that manipulates routes settings

**Comment by elcajon** [comment]
With the new web ui, it is also possible to use the following options when logging in via web ui (as an alternative to the URL in the log).

- custom login server --> could also be dropped from add-on config
- auth-key --> as previously requested by some users

**Comment by elcajon** [comment]
My observations regarding the read-only mode.

Accessing Tailscale Web ui via HA ingress (while local Windows/Mac/Linux Tailscale client is connected)

- from Tailscale proxy domain (provided by add-on)  --> not working
- from external domain (e.g. Cloudflare with correctly configured proxy headers) --> not working

exemplary screenshot
<img width="674" alt="image" src="https://github.com/lmagyar/homeassistant-addon-tailscale/assets/52052494/c083fb22-f51c-44d8-8a1a-1f6b3e729920">



- from local IP (e.g. 10.10.0.4:8123 - with and without routing subnets through Tailnet) --> working
- from Tailscale IP (e.g. 100.x.x.x:8123) --> working
- from Tailscale Domain without using proxy domain (e.g. homeassistant.funny-name.ts.net:8123) --> working

exemplary screenshot
<img width="674" alt="image" src="https://github.com/lmagyar/homeassistant-addon-tailscale/assets/52052494/6cdd19c7-97f4-4bc4-afe5-c40d34b62090">

I also did another test which result is quite interesting.

- Created a clean Debian based lxc container for this with only Tailscale installed
- Login to Tailscale 
- tailscale web --listen localhost:8088
- tailscale serve localhost:8088 (--> proxy Tailscale web ui)
- Open the https-serve-url
- UI is read-only

I would assume that the Tailscale Serve proxy is missing a possibility for proxy header to determine the client IP (on purpose or by mistake?), furthermore the client IP is the public IP when calling via an external domain, which apparently does not allow a login in the UI.

**Comment by lmagyar** [comment]
> from local IP (e.g. 10.10.0.4:8123 - with and without routing subnets through Tailnet) --> working

In my case only when browser's OS is connected to the tailnet.

> I would assume that the Tailscale Serve proxy is missing a possibility for proxy header to determine the client IP (on purpose or by mistake?), furthermore the client IP is the public IP when calling via an external domain, which apparently does not allow a login in the UI.

Hmmm. Or they especially determine the client IP, and that makes impossible to access non-read-only UI through reverse proxies??? Maybe they/we need some trusted_proxies setting for localhost in the `tailscale web` cli??? But there is no option for this. I'm just guessing, my experience is way too minimal to fix this problem.

**Comment by elcajon** [comment]
> In my case only when browser's OS is connected to the tailnet.

For me too, only the --accept-routes option is irrelevant.

> Hmmm. Or they especially determine the client IP, and that makes impossible to access non-read-only UI through reverse proxies??? Maybe they/we need some trusted_proxies setting for localhost in the tailscale web cli??? But there is no option for this. I'm just guessing, my experience is way too minimal to fix this problem.

Unfortunately, I can't say for sure, you would probably have to take a look at the corresponding coding of Tailscale's web server.

**Comment by lmagyar** [comment]
Disclaimer: I'm a total newbie in case of web development.

There are 2 thing going on.

## 1. How TS identifies the browser/user

As I see, some script running in the browser (when you press the "Viewing" button) tries to directly access `http://<device's TS IP>:5252/ok`, and when the browser is not part of the tailnet, certainly it fails. I see some workaround in the `tailscale web` source for synology and qnap to accept their user authentication.

So without a TS workaround for HA, I see 0 chance to access the non-read-only UI if the browser is not part of the tailnet.

## 2. Mixed content problem

When I access HA's plain http UI (browser -> HA/Ingress (http) -> add-on's nginx -> tailscale web), this `http://<device's TS IP>:5252/ok` request is worked if the browser was part of the tailnet.

When I access HA's **https** UI (browser -> nginx add-on (https) -> HA/Ingress (http) -> add-on's nginx -> tailscale web), this `http://<device's TS IP>:5252/ok` request is blocked with "(blocked:mixed-content)". As I understand the browser (Chrome) blocks the http request from a https page.

I have zero clue how to fix this. But this seems to be the side-effect of TS's home-made security code.

Maybe a workaround for HA in TS code can eliminate this http request and solve both issue.

So in my opinion it will never be fixed.

**Comment by lmagyar** [comment]
And when I access the plain http UI of HA and login/authenticate to see the non-read-only UI of TS web, it opens up a *new page* with `http://<device's TS IP>:5252/?check=now`

This will never work...

**Comment by lmagyar** [comment]
I "transferred" this issue to the original repo, maybe somebody knows better how to solve this. See: https://github.com/hassio-addons/addon-tailscale/issues/314
